services:
  mvo_contao_nested_forms.form_compiler:
    class: 'Mvo\ContaoNestedForms\Form\FormCompiler'

  mvo_contao_nested_forms.listener.datacontainer.form_field:
    class: 'Mvo\ContaoNestedForms\EventListener\DataContainer\FormField'
    arguments:
      - '@security.token_storage'
      - '@database_connection'