services:
  mvo_contao_nested_forms.form_compiler:
    class: 'Mvo\ContaoNestedForms\Form\FormCompiler'
    tags:
      - { name: 'contao.hook', hook: 'compileFormFields', method: 'onInject'}

  mvo_contao_nested_forms.listener.datacontainer.form_field:
    class: 'Mvo\ContaoNestedForms\EventListener\DataContainer\FormField'
    arguments:
      - '@security.token_storage'
      - '@database_connection'
    public: true